//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_relation
    {
        public int r_id { get; set; }
        public int r_my { get; set; }
        public int r_friend { get; set; }
    
        public virtual a_user a_user { get; set; }
        public virtual a_user a_user1 { get; set; }
    }
}
