//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_tag
    {
        public int t_id { get; set; }
        public string t_name { get; set; }
        public int t_upid { get; set; }
    
        public virtual a_upicture a_upicture { get; set; }
    }
}
