//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Service
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ablumEntities : DbContext
    {
        public ablumEntities()
            : base("name=ablumEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<a_ablum> a_ablum { get; set; }
        public DbSet<a_evaluation> a_evaluation { get; set; }
        public DbSet<a_picture> a_picture { get; set; }
        public DbSet<a_relation> a_relation { get; set; }
        public DbSet<a_tag> a_tag { get; set; }
        public DbSet<a_upicture> a_upicture { get; set; }
        public DbSet<a_user> a_user { get; set; }
    }
}
