//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_upicture
    {
        public a_upicture()
        {
            this.a_evaluation = new HashSet<a_evaluation>();
            this.a_tag = new HashSet<a_tag>();
        }
    
        public int up_id { get; set; }
        public string up_name { get; set; }
        public int up_pid { get; set; }
        public int up_abid { get; set; }
        public int up_power { get; set; }
        public System.DateTime up_uploadTime { get; set; }
        public int up_evaCount { get; set; }
        public string up_description { get; set; }
    
        public virtual a_ablum a_ablum { get; set; }
        public virtual ICollection<a_evaluation> a_evaluation { get; set; }
        public virtual a_picture a_picture { get; set; }
        public virtual ICollection<a_tag> a_tag { get; set; }
    }
}
