//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_Service
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_user
    {
        public a_user()
        {
            this.a_ablum = new HashSet<a_ablum>();
            this.a_evaluation = new HashSet<a_evaluation>();
            this.a_relation = new HashSet<a_relation>();
            this.a_relation1 = new HashSet<a_relation>();
        }
    
        public int u_id { get; set; }
        public string u_userName { get; set; }
        public string u_password { get; set; }
        public string u_Email { get; set; }
        public string u_Code { get; set; }
        public Nullable<int> u_pic { get; set; }
    
        public virtual ICollection<a_ablum> a_ablum { get; set; }
        public virtual ICollection<a_evaluation> a_evaluation { get; set; }
        public virtual ICollection<a_relation> a_relation { get; set; }
        public virtual ICollection<a_relation> a_relation1 { get; set; }
    }
}
